# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'starzPlayTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for starzPlayTest

  pod 'Alamofire', '~> 5.9'
  pod 'SDWebImage', '~> 5.19'

end
